server:
  port: 8081
eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://root:1234@localhost:27017/myapp?authSource=admin