eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://admin:admin@localhost:27017/myapp?authSource=admin
#      host: localhost
#      port: 27017
#      username: root
#      password: 1234
#      database: myapp