server:
  port: 9001
eureka:
  instance:
    hostname: 127.0.0.1
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: boardservice